parameters:
#    open_phone_book_web.example.class: OpenPhoneBook\WebBundle\Example

services:
#    open_phone_book_web.example:
#        class: %open_phone_book_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
